## 플레이스홀더와 변수

In [1]:
import tensorflow as tf

### 1) `tf.placeholder()`
* `tf.placeholder`: 계산을 실행할 때 입력값을 받는 변수로 사용
* `None`은 크기가 정해지지 않음을 의미

In [9]:
# X : 입력값 (input data)
X = tf.placeholder(tf.float32, [None, 3])
print(X)

Tensor("Placeholder_6:0", shape=(?, 3), dtype=float32)


In [8]:
# x_data: X placeholder에 넣을 값
# 두 번째 요소는 3개임
x_data = [[1, 2, 3], [4, 5, 6]]

### 2)` tf.Variable()`
* `tf.Variable:` 그래프를 계산하면서 최적화 할 변수들

In [10]:
# tf.random_normal: 각 변수들의 초기값을 정규분포를 따르는 랜덤값으로 초기화
W = tf.Variable(tf.random_normal([3, 2]))
b = tf.Variable(tf.random_normal([2, 1]))

# 입력값과 변수들을 계산할 수식 작성 X*W
expr = tf.matmul(X, W) + b

### 3) 그래프 실행

In [19]:
sess = tf.Session()
# 위에서 설정한 Variable 들의 값들을 초기화 하기 위해
# 그래프 실행시 tf.global_variables_initializer() 를 한번 실행해야함
sess.run(tf.global_variables_initializer())

In [20]:
print("=== x_data ===")
print(x_data)
print("=== W ===")
print(sess.run(W))
print("=== b ===")
print(sess.run(b))
print("=== expr ===")
# expr 수식에는 X라는 입력값 placeholder가 필요함
# 따라서 feed_dict 파라미터를 이용하여 dictionary 형태로 입력값을 넣어줘야함
print(sess.run(expr, feed_dict={X: x_data}))

sess.close()

=== x_data ===
[[1, 2, 3], [4, 5, 6]]
=== W ===
[[-0.32812771  0.06166669]
 [-1.38562131 -1.36309743]
 [ 1.78913689 -0.44513592]]
=== b ===
[[-0.46278834]
 [-1.15292823]]
=== expr ===
[[  1.80525208  -4.46272421]
 [  1.34127629 -10.39256382]]
